version: "3.8"
services:
  video-server:
    image: video-server:latest
    build:
      context: .
      dockerfile: build/server/Dockerfile
    network_mode: host
    restart: on-failure
    depends_on:
      mysqld:
        condition: service_healthy
    env_file: ./.env 
  mysqld:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=$SERVICE_DB_DATABASE
      - MYSQL_PASSWORD=$SERVICE_DB_PASSWORD
      - MYSQL_ROOT_PASSWORD=$SERVICE_DB_PASSWORD
    volumes:
      - mysqld-data:/var/lib/mysql
    ports:
      - '3306:3306'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

volumes:
  mysqld-data:
